#if !canImport(ObjectiveC)
import XCTest

extension SemaTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SemaTests = [
        ("testCheckFunctionDef", testCheckFunctionDef),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SemaTests.__allTests__SemaTests),
    ]
}
#endif
