#if !canImport(ObjectiveC)
import XCTest

extension CodeGenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodeGenTests = [
        ("testArgument", testArgument),
        ("testCodeGen", testCodeGen),
        ("testDecl", testDecl),
        ("testIf", testIf),
        ("testIfElse", testIfElse),
        ("testIfElsePrimitive", testIfElsePrimitive),
        ("testIfPrimitive", testIfPrimitive),
        ("testMinus", testMinus),
        ("testPlus", testPlus),
        ("testPrintAbcd", testPrintAbcd),
        ("testReturn", testReturn),
        ("testVar", testVar),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CodeGenTests.__allTests__CodeGenTests),
    ]
}
#endif
