#if !canImport(ObjectiveC)
import XCTest

extension ParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserTests = [
        ("testMultiDeclParse", testMultiDeclParse),
        ("testParse", testParse),
        ("testParseFunctionCall", testParseFunctionCall),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ParserTests.__allTests__ParserTests),
    ]
}
#endif
