#if !canImport(ObjectiveC)
import XCTest

extension ParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserTests = [
        ("testArgumentParse", testArgumentParse),
        ("testMultiDeclParse", testMultiDeclParse),
        ("testParseAddExpr", testParseAddExpr),
        ("testParse", testParse),
        ("testParseDecl", testParseDecl),
        ("testParseFunctionCall", testParseFunctionCall),
        ("testParseIf", testParseIf),
        ("testParseIfElse", testParseIfElse),
        ("testParseIfStatement", testParseIfStatement),
        ("testParseMultiPlus", testParseMultiPlus),
        ("testParseMultiPlusMinus", testParseMultiPlusMinus),
        ("testParseReturnFunc", testParseReturnFunc),
        ("testParseReturnStatement", testParseReturnStatement),
        ("testVarParse", testVarParse),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ParserTests.__allTests__ParserTests),
    ]
}
#endif
